[package]
name = "rush"
version = "0.1.0"
authors = ["Ian Shehadeh <IanShehadeh2020@gmail.com>"]
edition = "2021"

[dependencies]
nom = "4.1.1"
nix = "0.11.0"
lazy_static = "1.2.0"
failure = "0.1.3"
failure_derive = "0.1.3"
nixterm = "0.1.2"